instrument-type: Equity # No usage
region: USA # USA or CHN
universe: Top3000 # Top1000, Top500, Top200
delay: 1 # 1 or 0
neutralization: Market # None, Sector, Industry, Subindustry
decay: 30 # >= 0, integer
truncation: 0.01 # <= 0.1
pasteurization: True # True or False
unit-handling: verify # No usage
nan-handling: False # True or False
sample: test # test insample # insample, outsample, latest
temporary: True
